package view;

import model.Burger;
import model.List;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;

public class HomePage extends javax.swing.JFrame {

    public HomePage() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("HomePage");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        placeOrderbtn = new javax.swing.JButton();
        searchOrderbtn = new javax.swing.JButton();
        viewOrderbtn = new javax.swing.JButton();
        updateOrderDetailsbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        searchBestCustomerbtn = new javax.swing.JButton();
        searchCustomerbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        leftPanel.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to Burgers");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo2.png"))); // NOI18N

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        placeOrderbtn.setBackground(new java.awt.Color(232, 46, 46));
        placeOrderbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        placeOrderbtn.setForeground(new java.awt.Color(255, 255, 255));
        placeOrderbtn.setText("Place Order");
        placeOrderbtn.setBorder(null);
        placeOrderbtn.setBorderPainted(false);
        placeOrderbtn.setOpaque(true);
        placeOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderbtnActionPerformed(evt);
            }
        });

        searchOrderbtn.setBackground(new java.awt.Color(232, 46, 46));
        searchOrderbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchOrderbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchOrderbtn.setText("Search Order");
        searchOrderbtn.setBorder(null);
        searchOrderbtn.setOpaque(true);
        searchOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOrderbtnActionPerformed(evt);
            }
        });

        viewOrderbtn.setBackground(new java.awt.Color(232, 46, 46));
        viewOrderbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewOrderbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewOrderbtn.setText("View Orders");
        viewOrderbtn.setBorder(null);
        viewOrderbtn.setOpaque(true);
        viewOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderbtnActionPerformed(evt);
            }
        });

        updateOrderDetailsbtn.setBackground(new java.awt.Color(232, 46, 46));
        updateOrderDetailsbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateOrderDetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        updateOrderDetailsbtn.setText("Update Order Details");
        updateOrderDetailsbtn.setBorder(null);
        updateOrderDetailsbtn.setOpaque(true);
        updateOrderDetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateOrderDetailsbtnActionPerformed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(232, 46, 46));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("Exit");
        exitbtn.setBorder(null);
        exitbtn.setOpaque(true);

        searchBestCustomerbtn.setBackground(new java.awt.Color(232, 46, 46));
        searchBestCustomerbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBestCustomerbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBestCustomerbtn.setText("Search Best Customer");
        searchBestCustomerbtn.setBorder(null);
        searchBestCustomerbtn.setOpaque(true);
        searchBestCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBestCustomerbtnActionPerformed(evt);
            }
        });

        searchCustomerbtn.setBackground(new java.awt.Color(232, 46, 46));
        searchCustomerbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchCustomerbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchCustomerbtn.setText("Search Customer");
        searchCustomerbtn.setBorder(null);
        searchCustomerbtn.setOpaque(true);
        searchCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placeOrderbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchOrderbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewOrderbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateOrderDetailsbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBestCustomerbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchCustomerbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(placeOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBestCustomerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchCustomerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateOrderDetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderbtnActionPerformed
        new PlaceOrder().setVisible(true);
    }//GEN-LAST:event_placeOrderbtnActionPerformed

    private void searchBestCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBestCustomerbtnActionPerformed
        new SearchBestCustomer().setVisible(true);
    }//GEN-LAST:event_searchBestCustomerbtnActionPerformed

    private void searchOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOrderbtnActionPerformed
        new SearchOrderDetails().setVisible(true);
    }//GEN-LAST:event_searchOrderbtnActionPerformed

    private void searchCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerbtnActionPerformed
        new SearchCustomer().setVisible(true);
    }//GEN-LAST:event_searchCustomerbtnActionPerformed

    private void viewOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderbtnActionPerformed
        new ViewOrder().setVisible(true);
    }//GEN-LAST:event_viewOrderbtnActionPerformed

    private void updateOrderDetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateOrderDetailsbtnActionPerformed
        new UpdateOrder().setVisible(true);
    }//GEN-LAST:event_updateOrderDetailsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static List burgerList = new List();
    
    public static void main(String args[]) throws FileNotFoundException, IOException {
       new HomePage().setVisible(true);
       
       BufferedReader br = new BufferedReader(new FileReader("Order.txt"));
       
       String line;
       while((line = br.readLine()) != null){
           if(!line.trim().isEmpty()){
              String[] data = line.split(",");
              
              String orderId = data[0];
              String customerId = data[1];
              String name = data[2];
              int burgerQty = Integer.parseInt(data[3]);
              int status = Integer.parseInt(data[4]);
              
              Burger burger = new Burger(orderId,customerId,name,burgerQty,status);
              List intList = new List();
              intList.addLast(burger);
              
           }
       }
         br.close();
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JButton placeOrderbtn;
    private javax.swing.JButton searchBestCustomerbtn;
    private javax.swing.JButton searchCustomerbtn;
    private javax.swing.JButton searchOrderbtn;
    private javax.swing.JButton updateOrderDetailsbtn;
    private javax.swing.JButton viewOrderbtn;
    // End of variables declaration//GEN-END:variables

}
