
package view;

import controller.BurgerController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static controller.BurgerController.genarateOrderId;
import model.Burger;

public class PlaceOrder extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public PlaceOrder() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Place Order");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        orderIdlbl = new javax.swing.JLabel();
        customerIdlbl = new javax.swing.JLabel();
        qtylbl = new javax.swing.JLabel();
        statuslbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFPanel = new javax.swing.JPanel();
        placeOrderbtn = new javax.swing.JButton();
        backHomebtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        totaltex = new javax.swing.JTextField();
        orderIdtxt = new javax.swing.JTextField();
        customerIdtxt = new javax.swing.JTextField();
        qtytxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        statuslbl2 = new javax.swing.JLabel();
        newCustbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        orderIdlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        orderIdlbl.setText("Order ID :");

        customerIdlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerIdlbl.setText("Customer ID :");

        qtylbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qtylbl.setText("Burger QTY  :");

        statuslbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statuslbl.setText("Order Status :");

        jLabel2.setBackground(new java.awt.Color(255, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Place Order");
        jLabel2.setOpaque(true);

        textFPanel.setBackground(new java.awt.Color(255, 255, 255));

        placeOrderbtn.setBackground(new java.awt.Color(51, 255, 51));
        placeOrderbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        placeOrderbtn.setForeground(new java.awt.Color(255, 255, 255));
        placeOrderbtn.setText("Place Order");
        placeOrderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderbtnActionPerformed(evt);
            }
        });

        backHomebtn.setBackground(new java.awt.Color(255, 102, 102));
        backHomebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backHomebtn.setForeground(new java.awt.Color(255, 255, 255));
        backHomebtn.setText("Back To Home");
        backHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomebtnActionPerformed(evt);
            }
        });

        cancelbtn.setBackground(new java.awt.Color(255, 102, 102));
        cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelbtn.setText("Cancel");

        totaltex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totaltex.setForeground(new java.awt.Color(255, 102, 102));
        totaltex.setBorder(null);
        totaltex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout textFPanelLayout = new javax.swing.GroupLayout(textFPanel);
        textFPanel.setLayout(textFPanelLayout);
        textFPanelLayout.setHorizontalGroup(
            textFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textFPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(textFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placeOrderbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backHomebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totaltex, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        textFPanelLayout.setVerticalGroup(
            textFPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textFPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totaltex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, textFPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeOrderbtn)
                .addGap(18, 18, 18)
                .addComponent(backHomebtn)
                .addGap(19, 19, 19)
                .addComponent(cancelbtn)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        customerIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdtxtActionPerformed(evt);
            }
        });

        namelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namelbl.setText(" Name :");

        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        statuslbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statuslbl2.setText("Preparing.....");

        newCustbtn.setBackground(new java.awt.Color(255, 153, 0));
        newCustbtn.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        newCustbtn.setForeground(new java.awt.Color(255, 255, 255));
        newCustbtn.setText("New Customer");
        newCustbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NET Total :");

        totalTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalTxt.setForeground(new java.awt.Color(255, 51, 51));
        totalTxt.setBorder(null);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qtylbl)
                            .addComponent(statuslbl)
                            .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statuslbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qtytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderIdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerIdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(customerIdtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(orderIdtxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newCustbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(textFPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(textFPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(customerIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newCustbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statuslbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            orderIdtxt.setText(genarateOrderId());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        orderIdtxt.setEditable(false);
        customerIdtxt.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void customerIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdtxtActionPerformed
        String customerId = customerIdtxt.getText();
        boolean isHave = false;
        if(customerId.length() == 4){
            Burger burger = null;
            try {
                burger = BurgerController.searchCustomerId(customerId);
            } catch (IOException ex) {
                Logger.getLogger(PlaceOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(burger != null){
                nametxt.setText(burger.getCustomarName());
                qtytxt.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this,"Customer ID is Not found...");
                customerIdtxt.setText("");
            }
        
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Id...!");
            customerIdtxt.setText("");
        }
        /*if(!isHave){
            int op = JOptionPane.showConfirmDialog(this, "Do You want to add new customer?");
            if(op == JOptionPane.YES_OPTION){
                customerIdtxt.setText("");
                customerIdtxt.setText(genarateCustomerId());
                customerIdtxt.setEditable(false);
                nametxt.requestFocus();
            }
        }*/
    }//GEN-LAST:event_customerIdtxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        qtytxt.requestFocus();
    }//GEN-LAST:event_nametxtActionPerformed

    private void placeOrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderbtnActionPerformed

            int qty = Integer.parseInt(qtytxt.getText());
            String total = String.format("%.2f", (double)qty * model.Burger.UNIT_PRICE);
            totalTxt.setText(total);

            
            String orderId = orderIdtxt.getText();
            String custmerId = customerIdtxt.getText();
            String custName = nametxt.getText();
            int burgerQty = qty;
            int status = 0;
            
            boolean isAdd = controller.BurgerController.placeOrder(orderId, custmerId, custName, burgerQty, status);
            JOptionPane.showMessageDialog(this,"Order Placed Successfully...");
            
            if(!isAdd){
                JOptionPane.showMessageDialog(this, "Not Added!");
            }
            
        try {
            orderIdtxt.setText(genarateOrderId());
        } catch (IOException ex) {
            ex.printStackTrace();
        }
            customerIdtxt.setText("");
            customerIdtxt.setEditable(true);
            nametxt.setText("");
            qtytxt.setText("");
            totaltex.setText("");
            
    }//GEN-LAST:event_placeOrderbtnActionPerformed

    private void totaltexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltexActionPerformed
        
    }//GEN-LAST:event_totaltexActionPerformed

    private void backHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomebtnActionPerformed
       new HomePage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backHomebtnActionPerformed

    private void newCustbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustbtnActionPerformed
        customerIdtxt.setText(controller.BurgerController.genarateCustomerId());
        nametxt.requestFocus();
    }//GEN-LAST:event_newCustbtnActionPerformed
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backHomebtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel customerIdlbl;
    private javax.swing.JTextField customerIdtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JButton newCustbtn;
    private javax.swing.JLabel orderIdlbl;
    private javax.swing.JTextField orderIdtxt;
    private javax.swing.JButton placeOrderbtn;
    private javax.swing.JLabel qtylbl;
    private javax.swing.JTextField qtytxt;
    private javax.swing.JLabel statuslbl;
    private javax.swing.JLabel statuslbl2;
    private javax.swing.JPanel textFPanel;
    private javax.swing.JTextField totalTxt;
    private javax.swing.JTextField totaltex;
    // End of variables declaration//GEN-END:variables

}
