/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.*;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SearchOrderDetails extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public SearchOrderDetails() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Search Order Details");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        orderIdlbl = new javax.swing.JLabel();
        orderIdtxt = new javax.swing.JTextField();
        customerIdlbl = new javax.swing.JLabel();
        customerIdtxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        qtylbl = new javax.swing.JLabel();
        qtytxt = new javax.swing.JTextField();
        totallbl = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        statustxt = new javax.swing.JTextField();
        statuslbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Order Details");
        jLabel1.setOpaque(true);

        backbtn.setBackground(new java.awt.Color(255, 102, 102));
        backbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        orderIdlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderIdlbl.setText("Enter Order ID :");

        orderIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdtxtActionPerformed(evt);
            }
        });

        customerIdlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerIdlbl.setText("Customer ID :");

        customerIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdtxtActionPerformed(evt);
            }
        });

        namelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namelbl.setText("Name :");

        nametxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        qtylbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qtylbl.setText("QTY :");

        qtytxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qtytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtytxtActionPerformed(evt);
            }
        });

        totallbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totallbl.setText("Total :");

        totaltxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });

        statustxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statustxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statustxtActionPerformed(evt);
            }
        });

        statuslbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statuslbl.setText("Order Status :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(orderIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(orderIdtxt))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(customerIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(customerIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(qtylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(qtytxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(totallbl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totallbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void orderIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdtxtActionPerformed
        String orderId = orderIdtxt.getText();
        boolean isValid = false;
        if((orderId.length() != 4) || (orderId.charAt(0) != 'O' && orderId.charAt(0) != 'o')){
            JOptionPane.showMessageDialog(this, "Invalid Order ID...Please Re-Enter...");
            orderIdtxt.setText("");
            isValid = true;
        }
        if(!isValid){
            boolean found = false;
            String line;
            try {
                BufferedReader br = new BufferedReader(new FileReader("Order.txt"));
                while((line = br.readLine()) != null){
                    if(!line.trim().isEmpty()){
                        String[] data = line.split(",");
                        if(orderId.equalsIgnoreCase(data[0])){
                            found = true;
                            customerIdtxt.setText(data[1]);
                            customerIdtxt.setEditable(false);
                            nametxt.setText(data[2]);
                            nametxt.setEditable(false);
                            int qty = Integer.parseInt(data[3]);
                            qtytxt.setText(data[3]);
                            qtytxt.setEditable(false);
                            double total = qty * Burger.UNIT_PRICE;
                            totaltxt.setText(total+"");
                            totaltxt.setEditable(false);
                            String status = "";
                            switch(data[4]){
                                case "0":
                                    status = "Preparing...";
                                    break;
                                case "1":
                                    status = "Delivered...";
                                    break;
                                case "2":
                                    status = "Canceled...";
                                    break;   
                            }
                            statustxt.setText(status);
                            statustxt.setEditable(false);
                            break;
                        }
                    }
                }
                br.close();
                
             if(!found){
                JOptionPane.showMessageDialog(this, "Order ID is Not Found...");
            }
             
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "File is Not found...");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_orderIdtxtActionPerformed

    private void customerIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdtxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void qtytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtytxtActionPerformed

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed

    private void statustxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statustxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statustxtActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel customerIdlbl;
    private javax.swing.JTextField customerIdtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel orderIdlbl;
    private javax.swing.JTextField orderIdtxt;
    private javax.swing.JLabel qtylbl;
    private javax.swing.JTextField qtytxt;
    private javax.swing.JLabel statuslbl;
    private javax.swing.JTextField statustxt;
    private javax.swing.JLabel totallbl;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables

}
