/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.*;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class UpdateOrder extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public UpdateOrder() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Update Order");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        orderstatuslbl = new javax.swing.JLabel();
        statuscmb = new javax.swing.JComboBox<>();
        orderIdlbl = new javax.swing.JLabel();
        orderIdtxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        orderQtylbl = new javax.swing.JLabel();
        orderQtytxt = new javax.swing.JTextField();
        totallbl = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        customerIdlbl1 = new javax.swing.JLabel();
        customertxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Order");
        jLabel1.setOpaque(true);

        backbtn.setBackground(new java.awt.Color(255, 102, 102));
        backbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(51, 255, 51));
        updatebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("Update Order");
        updatebtn.setOpaque(true);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        orderstatuslbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderstatuslbl.setText("Order Status :");

        statuscmb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statuscmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preparing", "Delivered", "Canceled" }));

        orderIdlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderIdlbl.setText("Order ID :");

        orderIdtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdtxtActionPerformed(evt);
            }
        });

        namelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namelbl.setText("Name :");

        nametxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        orderQtylbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderQtylbl.setText("Order QTY :");

        orderQtytxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        totallbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totallbl.setText("Total :");

        totaltxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totaltxt.setForeground(new java.awt.Color(255, 51, 51));
        totaltxt.setBorder(null);

        customerIdlbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerIdlbl1.setText("Customer ID :");

        customertxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backbtn)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderstatuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(statuscmb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orderQtylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(orderQtytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totallbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(customerIdlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(customertxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(orderIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(orderIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderstatuslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statuscmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIdlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderIdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIdlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderQtylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderQtytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totallbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void orderIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdtxtActionPerformed
        String orderId = orderIdtxt.getText();
        boolean isValid = false;
        if((orderId.length() != 4) || (orderId.charAt(0) != 'O' && orderId.charAt(0) != 'o')){
            JOptionPane.showMessageDialog(this, "Invalid Order ID...Please Re-Enter...");
            orderIdtxt.setText("");
            isValid = true;
        }
        if(!isValid){
            boolean isFound = false;
            String line;
            try {
                BufferedReader br = new BufferedReader(new FileReader("Order.txt"));
                while((line = br.readLine()) != null){
                    if(!line.trim().isEmpty()){
                        String[] data = line.split(",");
                        if(orderId.equalsIgnoreCase(data[0])){
                            isFound = true;
                            int qty = Integer.parseInt(data[3]);
                            String total = String.format("%.2f", (double)qty * Burger.UNIT_PRICE);
                            switch(data[4]){
                                case "1":
                                    statuscmb.setSelectedIndex(1);
                                    statuscmb.setEnabled(false);
                                    customertxt.setText(data[1]);
                                    customertxt.setEditable(false);
                                    nametxt.setText(data[2]);
                                    nametxt.setEditable(false);
                                    orderQtytxt.setText(data[3]);
                                    orderQtytxt.setEditable(false);
                                    totaltxt.setText(total);
                                    totaltxt.setEditable(false);
                                    JOptionPane.showMessageDialog(this, "This Order is Already Delivered...");
                                    break;
                                
                                case "2":
                                    statuscmb.setSelectedIndex(2);
                                    statuscmb.setEnabled(false);
                                    customertxt.setText(data[1]);
                                    customertxt.setEditable(false);
                                    nametxt.setText(data[2]);
                                    nametxt.setEditable(false);
                                    orderQtytxt.setText(data[3]);
                                    orderQtytxt.setEditable(false);
                                    totaltxt.setText(total);
                                    totaltxt.setEditable(false);
                                    JOptionPane.showMessageDialog(this, "This Order is Already Canceled...");
                                    break;
                                    
                                case "0":
                                    statuscmb.setSelectedIndex(0);
                                    statuscmb.setEnabled(true);
                                    customertxt.setText(data[1]);
                                    customertxt.setEditable(false);
                                    nametxt.setText(data[2]);
                                    nametxt.setEditable(false);
                                    orderQtytxt.setText(data[3]);
                                    orderQtytxt.setEditable(true);
                                    totaltxt.setText(total);
                                    totaltxt.setEditable(false);
                                    break;
                                     
                            }
                        }
                    }
                }
                br.close();
                if(!isFound){
                    JOptionPane.showMessageDialog(this, "Order ID is Not Found...");
                }
                
            } catch (FileNotFoundException ex) {
                System.out.println("File Error...");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_orderIdtxtActionPerformed
    public int findIndex(){
        String orderId = orderIdtxt.getText();
        String line;
        int index = 0;
        try {
            BufferedReader br = new BufferedReader(new FileReader("Order.txt"));
            while((line = br.readLine()) != null){
                if(!line.trim().isEmpty()){
                    String[] data = line.split(",");
                    
                    if(orderId.equalsIgnoreCase(data[0])){
                       return index;
                    }
                }
                index++;
            }
            br.close();
        } catch (FileNotFoundException ex) {
            System.out.println("File Error...");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return -1;
    }
    
    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        int statusIndex = statuscmb.getSelectedIndex();
        int index = findIndex();
        int qty = Integer.parseInt(orderQtytxt.getText());
        String total = String.format("%.2f", (double)qty * Burger.UNIT_PRICE);
        totaltxt.setText(total);
        
        String orderId = orderIdtxt.getText();
        String customerId = customertxt.getText();
        String customerName = nametxt.getText();
        int burgerQty = qty;
        int status = statusIndex;
        
        Burger burger = new Burger(orderId,customerId,customerName,burgerQty,status);
        HomePage.burgerList.update(index,burger);
        
        JOptionPane.showMessageDialog(this, "Order Updated Successfully.!");
        try {
            FileWriter fw = new FileWriter("Order.txt");
            
            for(int i = 0; i < HomePage.burgerList.size(); i++){
                Burger b = HomePage.burgerList.get(i);
                
                fw.write(b.getOrderId()+","+ b.getCustomerId()+","+ b.getCustomarName()+","+ b.getBurgerQty()+","+ b.getStatus()+"\n");
            }
            fw.close();
            
            int selectIn = statuscmb.getSelectedIndex();
            switch(selectIn){
                case 1:
                    statuscmb.setEnabled(false);
                    orderQtytxt.setEditable(false);
                    break;
                case 2:
                    statuscmb.setEnabled(false);
                    orderQtytxt.setEditable(false);
                    break;
                default:
                    statuscmb.setEnabled(true);
                    orderQtytxt.setEditable(true);
            }
            
            
            
            
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel customerIdlbl1;
    private javax.swing.JTextField customertxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel orderIdlbl;
    private javax.swing.JTextField orderIdtxt;
    private javax.swing.JLabel orderQtylbl;
    private javax.swing.JTextField orderQtytxt;
    private javax.swing.JLabel orderstatuslbl;
    private javax.swing.JComboBox<String> statuscmb;
    private javax.swing.JLabel totallbl;
    private javax.swing.JTextField totaltxt;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

}
